# .Site config
baseurl = "https://www.hannasthoughts.com"
languageCode = "en-us"
title = "Hanna's Thoughts: Writings on a bunch of stuff I find interesting!"
description = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
paginate = 10
disqusShortname = "hannaliebl"
googleAnalytics = "UA-61564965-5"
canonifyurls = true

[author]
  name = "Hanna Liebl"

[taxonomies]
  tag = "tags"
  category = "categories"
  featured = "featured"

[markup.goldmark.renderer]
  unsafe= true

[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "dracula"
  tabWidth = 4

[permalinks]
  posts = "/:filename"
